/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface UiButton {
        "text": string;
    }
    interface UiCard {
        "text": string;
    }
    interface UiHome {
        "text": string;
    }
}
declare global {
    interface HTMLUiButtonElement extends Components.UiButton, HTMLStencilElement {
    }
    var HTMLUiButtonElement: {
        prototype: HTMLUiButtonElement;
        new (): HTMLUiButtonElement;
    };
    interface HTMLUiCardElement extends Components.UiCard, HTMLStencilElement {
    }
    var HTMLUiCardElement: {
        prototype: HTMLUiCardElement;
        new (): HTMLUiCardElement;
    };
    interface HTMLUiHomeElement extends Components.UiHome, HTMLStencilElement {
    }
    var HTMLUiHomeElement: {
        prototype: HTMLUiHomeElement;
        new (): HTMLUiHomeElement;
    };
    interface HTMLElementTagNameMap {
        "ui-button": HTMLUiButtonElement;
        "ui-card": HTMLUiCardElement;
        "ui-home": HTMLUiHomeElement;
    }
}
declare namespace LocalJSX {
    interface UiButton {
        "text"?: string;
    }
    interface UiCard {
        "text"?: string;
    }
    interface UiHome {
        "text"?: string;
    }
    interface IntrinsicElements {
        "ui-button": UiButton;
        "ui-card": UiCard;
        "ui-home": UiHome;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ui-button": LocalJSX.UiButton & JSXBase.HTMLAttributes<HTMLUiButtonElement>;
            "ui-card": LocalJSX.UiCard & JSXBase.HTMLAttributes<HTMLUiCardElement>;
            "ui-home": LocalJSX.UiHome & JSXBase.HTMLAttributes<HTMLUiHomeElement>;
        }
    }
}
